name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.4']
        node-version: ['22']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Run syntax check for JavaScript files
      run: |
        node -c lib/debounced/javascript/service.mjs
        node -c lib/debounced/javascript/server.mjs

    - name: Run RSpec tests
      run: bundle exec rspec

    - name: Capture system logs
      if: always()
      run: |
        mkdir -p logs
        cp debounced_proxy.log logs/ || true
        cp debounce_server.log logs/ || true
        echo "GitHub Actions runner environment" > logs/environment.log
        env >> logs/environment.log

    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ci-logs-${{ github.run_id }}
        path: logs/
        retention-days: 14
        compression-level: 9