name: Publish Gem

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'

    - name: Run tests
      run: bundle exec rspec
    
    - name: Build gem
      run: gem build *.gemspec

    - name: Publish to RubyGems
      run: gem push $(ls *.gem)
      env:
        GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}